"""
VENTUS // OAuth Token Fetcher
Run by SETUP.bat — do not run manually unless you know what you're doing.
Opens browser → Spotify login → catches callback → writes .env
"""
import sys, os, json, base64, urllib.parse, urllib.request, http.server, webbrowser, threading, time

CLIENT_ID     = sys.argv[1] if len(sys.argv) > 1 else ""
CLIENT_SECRET = sys.argv[2] if len(sys.argv) > 2 else ""
LFM_KEY       = sys.argv[3] if len(sys.argv) > 3 else ""
ENV_PATH      = sys.argv[4] if len(sys.argv) > 4 else ".env"

REDIRECT_URI  = "http://127.0.0.1:8888/callback"
SCOPES        = (
    "user-read-playback-state "
    "user-modify-playback-state "
    "user-read-currently-playing "
    "user-top-read "
    "playlist-read-private "
    "playlist-modify-public "
    "playlist-modify-private "
    "user-follow-read "
    "streaming"
)

auth_code = None
server_done = threading.Event()

class CallbackHandler(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a): pass   # silence access logs

    def do_GET(self):
        global auth_code
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path == "/callback":
            params = urllib.parse.parse_qs(parsed.query)
            if "code" in params:
                auth_code = params["code"][0]
                self.send_response(200)
                self.send_header("Content-Type", "text/html")
                self.end_headers()
                self.wfile.write(b"""
<html><head><style>
  body{margin:0;background:#080d14;font-family:monospace;display:flex;
       align-items:center;justify-content:center;height:100vh;color:#4db8ff;}
  h1{font-size:2rem;letter-spacing:.2em;}p{color:#a8d4ff88;}
</style></head><body>
  <div style="text-align:center">
    <h1>// SIGNAL ACQUIRED</h1>
    <p>Tokens written. You can close this window.</p>
    <p style="margin-top:2rem;color:#00e5cc">Return to SETUP to finish installation.</p>
  </div>
</body></html>""")
                server_done.set()
            elif "error" in params:
                err = params["error"][0]
                self.send_response(400)
                self.send_header("Content-Type", "text/html")
                self.end_headers()
                self.wfile.write(f"<html><body style='background:#080d14;color:#ff4444;font-family:monospace;padding:2rem'><h2>// AUTH ERROR: {err}</h2><p>Close this and re-run SETUP.bat</p></body></html>".encode())
                server_done.set()
        else:
            self.send_response(404)
            self.end_headers()

def exchange_code(code):
    creds = base64.b64encode(f"{CLIENT_ID}:{CLIENT_SECRET}".encode()).decode()
    data  = urllib.parse.urlencode({
        "grant_type":   "authorization_code",
        "code":         code,
        "redirect_uri": REDIRECT_URI,
    }).encode()
    req = urllib.request.Request(
        "https://accounts.spotify.com/api/token",
        data=data,
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type":  "application/x-www-form-urlencoded",
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        print(f"[ERROR] Token exchange HTTP {e.code}: {e.read().decode()}")
        return None
    except Exception as e:
        print(f"[ERROR] Token exchange failed: {e}")
        return None

def write_env(access_token, refresh_token):
    lines = [
        "# VENTUS // credentials — generated by SETUP.bat\n",
        f"SPOTIFY_CLIENT_ID={CLIENT_ID}\n",
        f"SPOTIFY_CLIENT_SECRET={CLIENT_SECRET}\n",
        f"SPOTIFY_REFRESH_TOKEN={refresh_token}\n",
        f"LFM_KEY={LFM_KEY}\n",
    ]
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"[OK] .env written to {ENV_PATH}")
    print(f"[OK] Refresh token: {refresh_token[:20]}...")
    print(f"[OK] Access token:  {access_token[:20]}...")

def main():
    if not CLIENT_ID or not CLIENT_SECRET:
        print("[ERROR] CLIENT_ID and CLIENT_SECRET required as arguments")
        sys.exit(1)

    # Build auth URL
    params = urllib.parse.urlencode({
        "client_id":     CLIENT_ID,
        "response_type": "code",
        "redirect_uri":  REDIRECT_URI,
        "scope":         SCOPES,
        "show_dialog":   "true",
    })
    auth_url = f"https://accounts.spotify.com/authorize?{params}"

    # Start callback server
    server = http.server.HTTPServer(("127.0.0.1", 8888), CallbackHandler)
    t = threading.Thread(target=server.serve_forever, daemon=True)
    t.start()

    print(f"\n[OAUTH] Opening browser for Spotify login...")
    print(f"[OAUTH] URL: {auth_url[:80]}...")
    time.sleep(0.5)
    webbrowser.open(auth_url)

    print("[OAUTH] Waiting for callback (timeout: 120s)...")
    got_it = server_done.wait(timeout=120)
    server.shutdown()

    if not got_it or not auth_code:
        print("[ERROR] Timed out or user cancelled auth. Run SETUP.bat again.")
        sys.exit(1)

    print("[OAUTH] Code received — exchanging for tokens...")
    tokens = exchange_code(auth_code)
    if not tokens or "refresh_token" not in tokens:
        print(f"[ERROR] Token exchange failed. Response: {tokens}")
        sys.exit(1)

    write_env(tokens["access_token"], tokens["refresh_token"])
    print("[OAUTH] ALL DONE — VENTUS is authorised.")
    sys.exit(0)

if __name__ == "__main__":
    main()
